### ISSUE TITLE
data customization

### ISSUE THREAD

**Issue by jose4n** [KChen89/Heartbeat-Classification-based-Diagnosis#2]
Hello again: D,
I wonder if it would be possible to customize the type of input data.
I am very interested in this project.

I attach the format of data i'd like to process.
[healthy_person1.txt](https://github.com/KChen89/Heartbeat-Classification-based-Diagnosis/files/2019809/healthy_person1.txt)
[disease_person1.txt](https://github.com/KChen89/Heartbeat-Classification-based-Diagnosis/files/2019810/disease_person1.txt)

**Comment by KChen89** [comment]
Thanks for your interest!  This is a general prototype for research purpose. The data used in this model is sampled at 360Hz and the model is pre-trained with eight types of heatbeat. Size and number of recognizable heartbeat types of the CNN model is fixed since it is a supervised learning model.  To customize it for your data. The QRS detection needs more parameter tuning to make it work to a acceptable level and the classification model needs redesign to fit your data sampling rate.

**Comment by jose4n** [comment]
So,l
if i could get data at 360 Hz there will be no problem?
I mean, my data ecg values are between 400 and 900, yours from -200 to 200

**Comment by KChen89** [comment]
You can try scaling and offset to your signal. 
Good luck!
K.C.
